import Anthropic from '@anthropic-ai/sdk';
import type { AnthropicMessage } from './cache.js';
import { estimateTokens } from '../pricing.js';

const HISTORY_TOKEN_LIMIT = 8_000;
const RECENT_TURNS_KEPT = 4; // keep last N turns verbatim

// ── Helpers ───────────────────────────────────────────────────────────────────

function messagesTokenCount(messages: AnthropicMessage[]): number {
  return messages.reduce((sum, msg) => {
    const text =
      typeof msg.content === 'string'
        ? msg.content
        : msg.content.map((b) => (b.text ?? '')).join('');
    return sum + estimateTokens(text);
  }, 0);
}

function messageToText(msg: AnthropicMessage): string {
  if (typeof msg.content === 'string') return msg.content;
  return msg.content.map((b) => (b.text ?? '')).join('');
}

// ── Main export ───────────────────────────────────────────────────────────────

/**
 * When the conversation history exceeds HISTORY_TOKEN_LIMIT tokens,
 * collapses all turns except the last RECENT_TURNS_KEPT into a single
 * summary generated by claude-haiku (cheap).
 */
export async function applyConversationSummarisation(
  messages: AnthropicMessage[],
  apiKey: string,
): Promise<{ messages: AnthropicMessage[]; summarised: boolean; tokensSaved: number }> {
  const totalTokens = messagesTokenCount(messages);

  if (totalTokens <= HISTORY_TOKEN_LIMIT || messages.length <= RECENT_TURNS_KEPT) {
    return { messages, summarised: false, tokensSaved: 0 };
  }

  const recentMessages = messages.slice(-RECENT_TURNS_KEPT);
  const oldMessages = messages.slice(0, -RECENT_TURNS_KEPT);

  if (oldMessages.length === 0) {
    return { messages, summarised: false, tokensSaved: 0 };
  }

  const oldTokens = messagesTokenCount(oldMessages);

  const conversationText = oldMessages
    .map((m) => `${m.role.toUpperCase()}: ${messageToText(m)}`)
    .join('\n\n');

  try {
    const client = new Anthropic({ apiKey });

    const resp = await client.messages.create({
      model: 'claude-haiku-4-5-20251001',
      max_tokens: 600,
      messages: [
        {
          role: 'user',
          content:
            'Summarise this conversation history concisely. Capture key decisions, ' +
            'context, code files discussed, and any important conclusions. Be brief.\n\n' +
            conversationText,
        },
      ],
    });

    const summaryText = resp.content
      .filter((b): b is Anthropic.TextBlock => b.type === 'text')
      .map((b) => b.text)
      .join('');

    const summaryMsg: AnthropicMessage = {
      role: 'user',
      content: `[Conversation summary — earlier turns collapsed]\n${summaryText}`,
    };

    const ackMsg: AnthropicMessage = {
      role: 'assistant',
      content: 'Understood — I have the prior conversation context.',
    };

    const newMessages: AnthropicMessage[] = [summaryMsg, ackMsg, ...recentMessages];
    const summaryTokens = messagesTokenCount([summaryMsg, ackMsg]);
    const tokensSaved = Math.max(0, oldTokens - summaryTokens);

    return { messages: newMessages, summarised: true, tokensSaved };
  } catch (err) {
    // Graceful degradation — return original messages unchanged
    console.error('[TokenDiff] Summarisation failed:', (err as Error).message);
    return { messages, summarised: false, tokensSaved: 0 };
  }
}
